package ru.cse.APILk.Service1c;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2022-08-17T16:38:40.395+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "SorterExchangePlanning", 
                  wsdlLocation = "http://lk-test.cse.ru/cargo3_test_it/ws/SorterExchangePlanning?wsdl",
                  targetNamespace = "http://www.cse-cargo.ru/client") 
public class SorterExchangePlanning extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cse-cargo.ru/client", "SorterExchangePlanning");
    public final static QName SorterExchangePlanningSoap12 = new QName("http://www.cse-cargo.ru/client", "SorterExchangePlanningSoap12");
    public final static QName SorterExchangePlanningSoap = new QName("http://www.cse-cargo.ru/client", "SorterExchangePlanningSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://lk-test.cse.ru/cargo3_test_it/ws/SorterExchangePlanning?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SorterExchangePlanning.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://lk-test.cse.ru/cargo3_test_it/ws/SorterExchangePlanning?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SorterExchangePlanning(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SorterExchangePlanning(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SorterExchangePlanning() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SorterExchangePlanning(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SorterExchangePlanning(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SorterExchangePlanning(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SorterExchangePlanningPortType
     */
    @WebEndpoint(name = "SorterExchangePlanningSoap12")
    public SorterExchangePlanningPortType getSorterExchangePlanningSoap12() {
        return super.getPort(SorterExchangePlanningSoap12, SorterExchangePlanningPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SorterExchangePlanningPortType
     */
    @WebEndpoint(name = "SorterExchangePlanningSoap12")
    public SorterExchangePlanningPortType getSorterExchangePlanningSoap12(WebServiceFeature... features) {
        return super.getPort(SorterExchangePlanningSoap12, SorterExchangePlanningPortType.class, features);
    }


    /**
     * 
     * 				
     * 			
     *
     * @return
     *     returns SorterExchangePlanningPortType
     */
    @WebEndpoint(name = "SorterExchangePlanningSoap")
    public SorterExchangePlanningPortType getSorterExchangePlanningSoap() {
        return super.getPort(SorterExchangePlanningSoap, SorterExchangePlanningPortType.class);
    }

    /**
     * 
     * 				
     * 			
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SorterExchangePlanningPortType
     */
    @WebEndpoint(name = "SorterExchangePlanningSoap")
    public SorterExchangePlanningPortType getSorterExchangePlanningSoap(WebServiceFeature... features) {
        return super.getPort(SorterExchangePlanningSoap, SorterExchangePlanningPortType.class, features);
    }

}
