package ru.cse.Meashuring.Service1c;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2021-10-29T14:30:18.538+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "MeasurerCargoPlanning", 
                  wsdlLocation = "http://adm-12/cse8_alexey/ws/MeasurerCargoPlanning?wsdl",
                  targetNamespace = "http://www.cse-cargo.ru/MeasurerCargo") 
public class MeasurerCargoPlanning extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cse-cargo.ru/MeasurerCargo", "MeasurerCargoPlanning");
    public final static QName MeasurerCargoPlanningSoap12 = new QName("http://www.cse-cargo.ru/MeasurerCargo", "MeasurerCargoPlanningSoap12");
    public final static QName MeasurerCargoPlanningSoap = new QName("http://www.cse-cargo.ru/MeasurerCargo", "MeasurerCargoPlanningSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://adm-12/cse8_alexey/ws/MeasurerCargoPlanning?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MeasurerCargoPlanning.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://adm-12/cse8_alexey/ws/MeasurerCargoPlanning?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MeasurerCargoPlanning(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MeasurerCargoPlanning(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeasurerCargoPlanning() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MeasurerCargoPlanning(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MeasurerCargoPlanning(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MeasurerCargoPlanning(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MeasurerCargoPlanningPortType
     */
    @WebEndpoint(name = "MeasurerCargoPlanningSoap12")
    public MeasurerCargoPlanningPortType getMeasurerCargoPlanningSoap12() {
        return super.getPort(MeasurerCargoPlanningSoap12, MeasurerCargoPlanningPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeasurerCargoPlanningPortType
     */
    @WebEndpoint(name = "MeasurerCargoPlanningSoap12")
    public MeasurerCargoPlanningPortType getMeasurerCargoPlanningSoap12(WebServiceFeature... features) {
        return super.getPort(MeasurerCargoPlanningSoap12, MeasurerCargoPlanningPortType.class, features);
    }


    /**
     * 
     * 				
     * 			
     *
     * @return
     *     returns MeasurerCargoPlanningPortType
     */
    @WebEndpoint(name = "MeasurerCargoPlanningSoap")
    public MeasurerCargoPlanningPortType getMeasurerCargoPlanningSoap() {
        return super.getPort(MeasurerCargoPlanningSoap, MeasurerCargoPlanningPortType.class);
    }

    /**
     * 
     * 				
     * 			
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeasurerCargoPlanningPortType
     */
    @WebEndpoint(name = "MeasurerCargoPlanningSoap")
    public MeasurerCargoPlanningPortType getMeasurerCargoPlanningSoap(WebServiceFeature... features) {
        return super.getPort(MeasurerCargoPlanningSoap, MeasurerCargoPlanningPortType.class, features);
    }

}
